### ISSUE TITLE
Website: 2 tab will confuse generating the share link

### ISSUE THREAD

**Issue by willie68** [wokwi/wokwi-docs#114]
If you have two tabs open in your browser, with different projects, the share button in each tab will alway generate a link for the last opened.

**Comment by urish** [comment]
Thanks Willie! I couldn't reproduce this behavior. Mind uploading a video showing it happening?

**Comment by willie68** [comment]
The day before yesterday it was easy to reproduce. Simply open 2 new tzabs on the browser, goto wokwi, login, goto my projects, select on every tab a different project, go on share and you got on both tabs the same id. (On one tab it was the right id, on the other it was the id from the other tab, not from the url. 
But now i can't reproduce it, too.
