### ISSUE TITLE
How can I translate wokwi-docs to Chinese?

### ISSUE THREAD

**Issue by breakeryu** [wokwi/wokwi-docs#120]
Hi!
I want to translate this doc to Chinese. How can I do this?

**Comment by breakeryu** [comment]
I think that I can join this project and share this great website with my friends.

**Comment by urish** [comment]
Thank you! What is your background? How familiar are you with GitHub?

@zhufree started to work on Chinese translation a few months ago, and translated a few pages (e.g. the [diagram editor page](https://github.com/wokwi/wokwi-docs/blob/master/i18n/zh-CN/docusaurus-plugin-content-docs/current/guides/diagram-editor.md)), but there's still much work to do - update the existing translations (they're more than 6 months old), and translate additional pages.

How would you like to work on it?

**Comment by zhufree** [comment]
Yes you can contact me for more information

**Comment by breakeryu** [comment]
> Yes you can contact me for more information

hi! zhu, I have sent an e-mail to your Gmail box.
