### ISSUE TITLE
wokwi-tm1637-7segment can't translate?

### ISSUE THREAD

**Issue by breakeryu** [wokwi/wokwi-docs#135]
I can't find wokwi-tm1637-7segment.md in zh-CN file. What can I do to fix this bug?

**Comment by urish** [comment]
Hi! It's a new part, added just last week (commit 9bbab4f047b2afedb1e6955149aadd1eeb6cd109). You can copy the file from the English version.

**Comment by breakeryu** [comment]
ok ， I get it。
