### ISSUE TITLE
Change Wokwi icon in the tab to white (in dark mode)

### ISSUE THREAD

**Issue by matititam** [wokwi/wokwi-docs#175]
It will be awesome if the docs tab also shows the Wokwi icon (w) in contrast font.. 

![image](https://user-images.githubusercontent.com/68117142/236467377-18c020ff-8d3d-4faa-a33a-98dcc4120aa7.png)

**Comment by urish** [comment]
Done

**Comment by luckyharvi** [comment]
how?
