### ISSUE TITLE
List of supported hardware

### ISSUE THREAD

**Issue by ygoe** [wokwi/wokwi-docs#177]
I got aware of this project by a news article today. Just had a quick look for now and I couldn't find out what devices the simulator supports, especially MCUs. I'm primarily using ESP32 and ATtiny1614. The latter is a relatively modern AVR 8-bit MCU that has some differences to the older Arduino models. I suggest adding a list of supported devices somewhere in the documentation, maybe link to it from the FAQ page.

**Comment by urish** [comment]
Hello, thanks for the suggestion. Added a page with the list of supported microcontrollers and other hardware:

https://docs.wokwi.com/getting-started/supported-hardware

I'm curious - which news article mentioned Wokwi?
