### ISSUE TITLE
Attiny85 and tone

### ISSUE THREAD

**Issue by staltux** [wokwi/wokwi-docs#190]
the tone function is not working on Attiny85

using an arduino works

the test with attiny85

https://wokwi.com/projects/380875729611174913

the same code on an arduino

https://wokwi.com/projects/380875832702983169

using only digitalWrite and delay the buzzer works

**Comment by urish** [comment]
Thanks for reporting!

tone() does not work on the default ATTiny85 core - it is not a simulation problem, it also doesn't on the actual ATtiny85 device. See here: https://forum.arduino.cc/t/attiny-and-tone/430648/37

Using `digitalWrite` is actually a good way to overcome this - here's an example implementation of `beep()` that uses the same method: https://wokwi.com/projects/285525640477671948
