### ISSUE TITLE
Docs : board-ssd1306 Reference(Chinese)

### ISSUE THREAD

**Issue by art20040423** [wokwi/wokwi-docs#192]
[board-ssd1306 Reference(Chinese)](https://docs.wokwi.com/zh-CN/parts/board-ssd1306)
 Using in Arduino部分連結有問題，重導到 [wokwi.com](https://wokwi.com/)

**Comment by urish** [comment]
thanks for reporting, fixed.

**Comment by art20040423** [comment]
fixed?
後來發現，在專案里改語言並不會改變網址
英文版([board-ssd1306 Reference(English)](https://docs.wokwi.com/parts/board-ssd1306#))連結是沒錯的，所以把中文版連結改成跟英文版一樣，也許就可以修復問題。

**Comment by urish** [comment]
Yes, I changed the Chinese link to match the English version

**Comment by art20040423** [comment]
很奇怪，在[wokwi-dht22 Reference(Chinese)](https://docs.wokwi.com/zh-CN/parts/wokwi-dht22)，的[DHTlib DHT22 test](https://wokwi.com/arduino/libraries/DHTlib/dht22_test)卻可以順利跳轉。

**Comment by art20040423** [comment]
嘗試了一下，但按[board-ssd1306：编辑此页面](https://github.com/wokwi/wokwi-docs/edit/main/docs/parts/board-ssd1306.md)，卻是跳到英文
