### ISSUE TITLE
wokwi-text missing as standard-part

### ISSUE THREAD

**Issue by wvsbsp** [wokwi/wokwi-docs#196]
In some projects i found the part "wokwi-text" for labeling parts. Why isn't such a basic thing in the parts-list? If there is a hotkey to input texts - i haven't found it / won't remerber it long ;-)
At thet time, i copy/paste this part from old projects an edit it in the .json...

best regards 
Bernhard

**Comment by urish** [comment]
Yeah, it's not yet completed. See wokwi/wokwi-features#43. Once it's completed, it'll also be documented.
