### ISSUE TITLE
[Documentation] Example to show static and multiplexed signals for 7-segment displays.

### ISSUE THREAD

**Issue by Koepel** [wokwi/wokwi-docs#201]
Documentation: https://docs.wokwi.com/parts/wokwi-7segment
My example: https://wokwi.com/projects/397598198000164865

Could my example be added to the documentation ?
It is to show the 7-segment displays controlled by either static signals or multiplexed signals without libraries to show the difference.

**Comment by Koepel** [comment]
It is called "7-Segment without a library on Arduino Mega", but that is not its purpose.
In the documentation, it is mentioned that a single digit requires 8 GPIO pins and multiple digits can be tricky. My example is to show the difference between non-multiplexed signals with static digital GPIO pins and multiplexed signals which need to keep the display updated with a delay.

Could you change the text ?

**Comment by urish** [comment]
Can you please suggest an alternative text?

**Comment by Koepel** [comment]
I gave the Wokwi project the title: Static versus Multiplexed signals for 7-segment displays.
