### ISSUE TITLE
All links to boards are parts

### ISSUE THREAD

**Issue by georgik** [wokwi/wokwi-docs#221]
URL: https://docs.wokwi.com/diagram-format/
Links like: https://docs.wokwi.com/diagram-format/parts/wokwi-attiny85

Points to: 
```
Page Not Found
We could not find what you were looking for.

Please contact the owner of the site that linked you to the original URL and let them know their link is broken.
```

The error is not 404, so lychee is not able to discover it.

**Comment by urish** [comment]
Fixed! Thanks for reporting.
