### ISSUE TITLE
Improving the documentation about the serial monitor

### ISSUE THREAD

**Issue by StefanL38** [wokwi/wokwi-docs#58]
The Wiki of Woki about the serial monitor is not detailed enough
https://docs.wokwi.com/guides/serial-monitor#display
there is a missing comma at the end of the code

`"serialMonitor": {
  "display": "auto",
  "newline": "lf"
}`

behind the closing curly bracket there is a comma needed.
`"serialMonitor": {
  "display": "auto",
  "newline": "lf"
},`

Even better would be to show not only this code-snippet you have to insert but to show a short but completed JSON-file to make visible where and how to insert the serialMonitor-section.

That I have to write this issue is caused by an effect I call "the expert-blindness-for-beginners-difficulties" 
To somebody who knows JSON-files very well the short description is enough. But not for beginners.

If your help-files shall be really helpful review them from the knowledge of a real beginner
best regards Stefan

**Comment by urish** [comment]
Thanks for the suggestions! I updated the docs to note about the comma, and also linked to a complete example.
