### ISSUE TITLE
Scrolling issue

### ISSUE THREAD

**Issue by arcostasi** [wokwi/wokwi-docs#95]
I was having this problem with scrolling in the Wokwi docs.

**Solution:** I turned disabled the option **Experimental Web Platform features** 
(_chrome://flags/#enable-experimental-web-platform-features)_)

**More details**: [Scrolling issue since beta.15](https://github.com/facebook/docusaurus/issues/6587)

**Comment by urish** [comment]
Thanks for reporting Anderson!

In the meanwhile, I reverted to beta.14. Can you please check if this still happens?

**Comment by arcostasi** [comment]
> In the meanwhile, I reverted to beta.14. Can you please check if this still happens?

Hi Uri, I enabled again the option **Experimental Web Platform features** and the problem did not occur! 
Scrolling works correctly again! thanks

**Comment by urish** [comment]
Lovely, thanks for checking :)
